const quotes = [
    "Excelsior! - Stan Lee",
    "To be a hero, you don't have to be super, you just have to be brave for a little bit longer than everyone else. - Auggie Pullman (Wonder)",
    "I am the night. I am Batman! - Batman",
    "With great power comes great responsibility. - Spider-Man",
    "It's not who I am underneath, but what I do that defines me. - Batman",
    "I'm the best there is at what I do, but what I do best isn't very nice. - Wolverine",
    "Hulk smash! - Hulk",
    "I am Iron Man. - Iron Man",
    "I'm not locked in here with you. You're locked in here with me! - Rorschach",
    "Avengers assemble! - Captain America",
    "I'm the Doctor. I'm a Time Lord. I'm from the planet Gallifrey in the constellation of Kasterborous. - The Doctor",
    "I am Groot. - Groot",
    "I am vengeance. I am the night. I am Batman! - Batman",
    "I am the law! - Judge Dredd",
    "I'm not a hero. I'm a person who's trying to do the right thing. - Hawkeye",
    "I am the darkness. - Daredevil",
    "I will fight for those who cannot fight for themselves. - Wonder Woman",
    "I'm the fastest man alive. - The Flash",
    "It's clobberin' time! - The Thing",
    "You don't get another chance. Life is no Nintendo game. - Eminem",
    "We are Venom! - Venom",
    "I have a plan. - Iron Man",
    "I'm not the one that needs to watch their back. - Black Widow",
    "I am inevitable. - Thanos",
    "You get what anyone gets - you get a lifetime. - Death (from 'Sandman' comics)",
    "I am the smartest man in the world. - Doctor Manhattan",
    "The night is darkest just before the dawn. And I promise you, the dawn is coming. - Harvey Dent",
    "In brightest day, in blackest night, no evil shall escape my sight. Let those who worship evil's might, beware my power, Green Lantern's light! - Green Lantern oath",
    "I'm Batman, and that's all that matters. - Batman",
    "I'm the best at what I do, and what I do isn't very nice. - Wolverine",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt (quoted by Batman in 'The Long Halloween')",
    "My parents taught me a different way of seeing things. - T'Challa (Black Panther)",
    "Sometimes the truth isn't good enough, sometimes people deserve more. Sometimes people deserve to have their faith rewarded. - Batman",
    "I am your father. - Darth Vader (Star Wars comic)",
    "You're not the only one cursed with knowledge. - Thanos",
    "I know what it's like to lose. To feel so desperately that you're right, yet to fail nonetheless. - Thanos",
    "I can do this all day. - Captain America",
    "My power is the power of a god. And you, my friend, are about to find out what that feels like. - Thor",
    "I am the Flash. - The Flash"]

    function newQuote() {
        var randomNumber = Math.floor(Math.random() * (quotes.length));
        document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
    };